USE STAGE;

SELECT COUNT(*) TOTAL_REGISTROS
, SUM(CASE WHEN LENGTH(TRIM(ID)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_ID
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(ID)) <> 0 THEN ID ELSE 0 END) AS TOTAL_DISTINTOS_ID
, SUM(CASE WHEN LENGTH(TRIM(`ORDER`)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_ORDER
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(`ORDER`)) <> 0 THEN `ORDER` ELSE 0 END) AS TOTAL_DISTINTOS_ORDER
, SUM(CASE WHEN LENGTH(TRIM(PHASE)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_PHASE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PHASE)) <> 0 THEN PHASE ELSE 0 END) AS TOTAL_DISTINTOS_PHASE
, SUM(CASE WHEN LENGTH(TRIM(AGENT)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_AGENT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AGENT)) <> 0 THEN AGENT ELSE 0 END) AS TOTAL_DISTINTOS_AGENT
, SUM(CASE WHEN LENGTH(TRIM(START_DT)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_START_DT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(START_DT)) <> 0 THEN START_DT ELSE 0 END) AS TOTAL_DISTINTOS_START_DT
, SUM(CASE WHEN LENGTH(TRIM(END_DT)) <> 0 THEN 1 ELSE 0 END) AS TOTAL_END_DT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(END_DT)) <> 0 THEN END_DT ELSE 0 END) AS TOTAL_DISTINTOS_END_DT
FROM STAGE.STG_ORDERS_CRM;



