USE ODS;

DROP TABLE IF EXISTS ODS_DM_CANALES;

CREATE TABLE ODS_DM_CANALES
(ID_CANAL INT unsigned auto_increment PRIMARY KEY
, DE_CANAL VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_PRODUCTOS;

CREATE TABLE ODS_DM_PRODUCTOS
(ID_PRODUCTO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_PRODUCTO VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_HC_SERVICIOS;

CREATE TABLE ODS_HC_SERVICIOS
(ID_SERVICIO INT NOT NULL PRIMARY KEY
, ID_CLIENTE INT(11)
, ID_PRODUCTO INT(10)
, PUNTO_ACCESO VARCHAR(512)
, ID_CANAL INT(10)
, ID_AGENTE INT(11)
, ID_DIRECCION_SERVICIO INT(10)
, FC_INICIO DATETIME
, FC_INSTALACION DATETIME
, FC_FIN DATETIME
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

