USE ODS;

DROP TABLE IF EXISTS ODS_DM_FASES;

CREATE TABLE ODS_DM_FASES
(ID_FASE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_FASE VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_AGENTES_PROV;

CREATE TABLE ODS_DM_AGENTES_PROV
(ID_AGENTE_PROV INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_AGENTE_PROV VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_HC_PROVISIONES;

CREATE TABLE ODS_HC_PROVISIONES
(
ID_PROVISION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, ID INT(11)
, ID_SERVICIO INT(11)
, ID_FASE INT(11)
, ID_AGENTE_PROV INT(10) UNSIGNED
, FC_INICIO DATETIME
, FC_FIN DATETIME
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);
 