USE ODS;

DROP TABLE IF EXISTS ODS_DM_DEPARTAMENTOS_CC;

CREATE TABLE ODS_DM_DEPARTAMENTOS_CC
(ID_DEPARTAMENTO_CC INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_DEPARTAMENTO_CC VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_AGENTES_CC;

CREATE TABLE ODS_DM_AGENTES_CC
(ID_AGENTE_CC INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_AGENTE_CC VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_HC_LLAMADAS;

CREATE TABLE ODS_HC_LLAMADAS
(
ID_LLAMADA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, ID_IVR INT(11)
, TELEFONO_LLAMADA BIGINT(20)
, ID_CLIENTE INT(11)
, FC_INICIO_LLAMADA DATETIME
, FC_FIN_LLAMADA DATETIME
, ID_DEPARTAMENTO_CC INT(10) UNSIGNED
, FLG_TRANSFERIDO TINYINT(1)
, ID_AGENTE_CC INT(10) UNSIGNED
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);
 