USE ODS;

ALTER TABLE ODS.ODS_HC_PROVISIONES ADD INDEX FK_PROV_SER_IDX (ID_SERVICIO ASC);
ALTER TABLE ODS.ODS_HC_PROVISIONES ADD CONSTRAINT FK_PROV_SER FOREIGN KEY (ID_SERVICIO)
  REFERENCES ODS.ODS_HC_SERVICIOS (ID_SERVICIO);

ALTER TABLE ODS.ODS_HC_PROVISIONES ADD INDEX FK_FASE_IDX (ID_FASE ASC);
ALTER TABLE ODS.ODS_HC_PROVISIONES CHANGE COLUMN ID_FASE ID_FASE INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_PROVISIONES ADD CONSTRAINT FK_FASE FOREIGN KEY (ID_FASE)
  REFERENCES ODS.ODS_DM_FASES (ID_FASE);

ALTER TABLE ODS.ODS_HC_PROVISIONES ADD INDEX FK_PROV_AGEN_IDX (ID_AGENTE_PROV ASC);
ALTER TABLE ODS.ODS_HC_PROVISIONES ADD CONSTRAINT FK_PROV_AGEN FOREIGN KEY (ID_AGENTE_PROV)
  REFERENCES ODS.ODS_DM_AGENTES_PROV (ID_AGENTE_PROV);
