USE ODS;

ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX FK_LLA_CLI_IDX (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT FK_LLA_CLI FOREIGN KEY (ID_CLIENTE)
  REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE);

ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX FK_LLA_DEP_IDX (ID_DEPARTAMENTO_CC ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT FK_LLA_DEP FOREIGN KEY (ID_DEPARTAMENTO_CC)
  REFERENCES ODS.ODS_DM_DEPARTAMENTOS_CC (ID_DEPARTAMENTO_CC);

ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX FK_LLA_AGEN_IDX (ID_AGENTE_CC ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT FK_LLA_AGEN FOREIGN KEY (ID_AGENTE_CC)
  REFERENCES ODS.ODS_DM_AGENTES_CC (ID_AGENTE_CC);
