USE ODS;

ALTER TABLE ODS.ODS_HC_FACTURAS ADD INDEX FK_FAC_CLI_IDX (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_FACTURAS ADD CONSTRAINT FK_FAC_CLI FOREIGN KEY (ID_CLIENTE)
  REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE);

ALTER TABLE ODS.ODS_HC_FACTURAS CHANGE COLUMN ID_METODO_PAGO ID_METODO_PAGO INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_FACTURAS ADD INDEX FK_FAC_MET_IDX (ID_METODO_PAGO ASC);
ALTER TABLE ODS.ODS_HC_FACTURAS ADD CONSTRAINT FK_FAC_MET FOREIGN KEY (ID_METODO_PAGO)
  REFERENCES ODS.ODS_DM_METODOS_PAGO (ID_METODO_PAGO);

ALTER TABLE ODS.ODS_HC_FACTURAS CHANGE COLUMN ID_CICLO_FACTURACION ID_CICLO_FACTURACION INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_FACTURAS ADD INDEX FK_FAC_CIC_IDX (ID_CICLO_FACTURACION ASC);
ALTER TABLE ODS.ODS_HC_FACTURAS ADD CONSTRAINT FK_FAC_CIC FOREIGN KEY (ID_CICLO_FACTURACION)
  REFERENCES ODS.ODS_DM_CICLOS_FACTURACION (ID_CICLO_FACTURACION);
  
