USE ODS;

DROP TABLE IF EXISTS TMP_DIR_SERVICIO;

CREATE TABLE TMP_DIR_SERVICIO AS
SELECT DIR.ID_DIRECCION,
DIR.DE_DIRECCION,
DIR.DE_CP,
CIU.DE_CIUDAD,
CIU.DE_ESTADO,
PAI.DE_PAIS
FROM ODS.ODS_HC_DIRECCIONES DIR
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADO CIU ON DIR.ID_CIUDAD_ESTADO = CIU.ID_CIUDAD_ESTADO
INNER JOIN ODS.ODS_DM_PAISES PAI ON CIU.ID_PAIS = PAI.ID_PAIS;

ANALYZE TABLE TMP_DIR_SERVICIO;


DROP TABLE IF EXISTS TMP_DIR_SERVICIO2;

CREATE TABLE TMP_DIR_SERVICIO2 AS
SELECT PRO.PRODUCT_ID
, DIR.ID_DIRECCION
FROM STAGE.STG_PRODUCTOS_CRM PRO
INNER JOIN ODS.TMP_DIR_SERVICIO DIR ON CASE WHEN TRIM(PRO.PRODUCT_ADDRESS)<>'' THEN UPPER(TRIM(PRO.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END = DIR.DE_DIRECCION
AND CASE WHEN TRIM(PRO.PRODUCT_POSTAL_CODE)<>'' THEN TRIM(PRO.PRODUCT_POSTAL_CODE) ELSE 99999 END = DIR.DE_CP
AND CASE WHEN TRIM(PRO.PRODUCT_STATE)<>'' THEN UPPER(TRIM(PRO.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END = DIR.DE_ESTADO
AND CASE WHEN TRIM(PRO.PRODUCT_CITY)<>'' THEN UPPER(TRIM(PRO.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END = DIR.DE_CIUDAD
AND CASE WHEN TRIM(PRO.PRODUCT_COUNTRY)<>'' THEN UPPER(TRIM(REPLACE(PRO.PRODUCT_COUNTRY,'United States','US'))) ELSE 'DESCONOCIDO' END = DIR.DE_PAIS;

ANALYZE TABLE TMP_DIR_SERVICIO2;

INSERT INTO ODS.ODS_HC_SERVICIOS
SELECT SER.PRODUCT_ID ID_SERVICIO
, CASE WHEN CLI.ID_CLIENTE IS NULL THEN CAST(LPAD(CUSTOMER_ID,9,9) AS SIGNED INTEGER) ELSE ID_CLIENTE END ID_CLIENTE
, PRO.ID_PRODUCTO
, ACCESS_POINT PUNTO_ACCESO
, CA.ID_CANAL
, CASE WHEN TRIM(SER.AGENT_CODE)='' THEN 9998 ELSE SER.AGENT_CODE END ID_AGENTE
, ID_DIRECCION
, CASE WHEN TRIM(SER.START_DATE) = '' THEN STR_TO_DATE('31/12/9999','%d/%m/%Y') ELSE STR_TO_DATE(SER.START_DATE,'%d/%m/%Y') END FC_INICIO
, CASE WHEN TRIM(SER.INSTALL_DATE) = '' THEN STR_TO_DATE('31/12/9998','%d/%m/%Y') ELSE STR_TO_DATE(SUBSTRING(INSTALL_DATE, 1,19),'%Y-%m-%d %H:%i:%s') END FC_INSTALACION 
, CASE WHEN TRIM(SER.END_DATE) = '' THEN STR_TO_DATE('31/12/9998','%d/%m/%Y') ELSE STR_TO_DATE(SUBSTRING(END_DATE, 1,19),'%Y-%m-%d %H:%i:%s') END FC_FIN 
, NOW()
, STR_TO_DATE('31/12/9998','%d/%m/%Y')
FROM STAGE.STG_PRODUCTOS_CRM SER
LEFT JOIN ODS.ODS_HC_CLIENTES CLI ON CLI.ID_CLIENTE = SER.CUSTOMER_ID
INNER JOIN ODS.ODS_DM_PRODUCTOS PRO ON CASE WHEN TRIM(SER.PRODUCT_NAME)<>'' THEN UPPER(TRIM(SER.PRODUCT_NAME)) ELSE 'DESCONOCIDO' END = PRO.DE_PRODUCTO
INNER JOIN ODS.ODS_DM_CANALES CA ON CASE WHEN TRIM(SER.CHANNEL)<>'' THEN UPPER(TRIM(SER.CHANNEL)) ELSE 'DESCONOCIDO' END = CA.DE_CANAL
INNER JOIN ODS.TMP_DIR_SERVICIO2 DIR ON DIR.PRODUCT_ID = SER.PRODUCT_ID;

COMMIT;

ANALYZE TABLE ODS.ODS_HC_SERVICIOS;

DROP TABLE ODS.TMP_DIR_SERVICIO;
DROP TABLE ODS.TMP_DIR_SERVICIO2;





