USE ODS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_CLIENTES;

CREATE TABLE TMP_DIRECCIONES_CLIENTES AS 
SELECT DIR.ID_DIRECCION
, DIR.DE_DIRECCION
, DIR.DE_CP
, CIU.DE_CIUDAD
, CIU.DE_ESTADO
, PAI.DE_PAIS
FROM ODS.ODS_HC_DIRECCIONES DIR
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADO CIU ON DIR.ID_CIUDAD_ESTADO=CIU.ID_CIUDAD_ESTADO
INNER JOIN ODS.ODS_DM_PAISES PAI ON CIU.ID_PAIS=PAI.ID_PAIS;

ANALYZE TABLE TMP_DIRECCIONES_CLIENTES;

DROP TABLE IF EXISTS TMP_DIR_SERVICIO;

CREATE TABLE TMP_DIR_SERVICIO AS
SELECT DISTINCT CASE WHEN TRIM(PRODUCT_ADDRESS)<>'' THEN UPPER(TRIM(PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END PRODUCT_ADDRESS
, CASE WHEN TRIM(PRODUCT_POSTAL_CODE)<>'' THEN UPPER(TRIM(PRODUCT_POSTAL_CODE)) ELSE 99999 END PRODUCT_POSTAL_CODE 
, CASE WHEN TRIM(PRODUCT_CITY)<>'' THEN UPPER(TRIM(PRODUCT_CITY)) ELSE 'DESCONOCIDO' END PRODUCT_CITY
, CASE WHEN TRIM(PRODUCT_STATE)<>'' THEN UPPER(TRIM(PRODUCT_STATE)) ELSE 'DESCONOCIDO' END PRODUCT_STATE
, CASE WHEN TRIM(PRODUCT_COUNTRY)<>'' THEN UPPER(TRIM(REPLACE(PROD.PRODUCT_COUNTRY,'United States','US'))) ELSE 'DESCONOCIDO' END  PRODUCT_COUNTRY
FROM STAGE.STG_PRODUCTOS_CRM PROD
WHERE TRIM(PRODUCT_ADDRESS)<>'' OR TRIM(PRODUCT_POSTAL_CODE)<>'' OR TRIM(PRODUCT_CITY)<>'' OR TRIM(PRODUCT_STATE)<>'' OR TRIM(PRODUCT_COUNTRY)<>''
;

DROP TABLE IF EXISTS TMP_DIR_SERVICIO2;

CREATE TABLE TMP_DIR_SERVICIO2 AS
SELECT PRODUCT_ADDRESS, PRODUCT_POSTAL_CODE, PRODUCT_CITY, PRODUCT_STATE, PRODUCT_COUNTRY
FROM TMP_DIR_SERVICIO SERV 
LEFT OUTER JOIN TMP_DIRECCIONES_CLIENTES CLI ON CONCAT(PRODUCT_ADDRESS, PRODUCT_POSTAL_CODE, PRODUCT_CITY, PRODUCT_STATE, PRODUCT_COUNTRY)=CONCAT(DE_DIRECCION, DE_CP, DE_CIUDAD, DE_ESTADO, DE_PAIS)
WHERE CONCAT(DE_DIRECCION, DE_CP, DE_CIUDAD, DE_ESTADO, DE_PAIS) IS NULL;

INSERT INTO ODS_DM_PAISES (DE_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT PAI.DE_PAIS, NOW(), NOW()
FROM TMP_DIR_SERVICIO2 DIR
INNER JOIN ODS.ODS_DM_PAISES PAI ON DIR.PRODUCT_COUNTRY=PAI.DE_PAIS
LEFT OUTER JOIN TMP_DIRECCIONES_CLIENTES CLI ON PRODUCT_COUNTRY=CLI.DE_PAIS
WHERE CLI.DE_PAIS IS NULL;

COMMIT;

INSERT INTO ODS_DM_CIUDADES_ESTADO (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT PRODUCT_CITY, PRODUCT_STATE, PAI.ID_PAIS, NOW(), NOW()
FROM TMP_DIR_SERVICIO2 DIR
INNER JOIN ODS.ODS_DM_PAISES PAI ON DIR.PRODUCT_COUNTRY=PAI.DE_PAIS
LEFT OUTER JOIN TMP_DIRECCIONES_CLIENTES CLI ON CONCAT(PRODUCT_CITY, PRODUCT_STATE, PRODUCT_COUNTRY)=CONCAT(CLI.DE_CIUDAD, CLI.DE_ESTADO, CLI.DE_PAIS)
WHERE CONCAT(CLI.DE_CIUDAD, CLI.DE_ESTADO, CLI.DE_PAIS) IS NULL;

COMMIT;

UPDATE ODS_DM_CIUDADES_ESTADO SET ID_CIUDAD_ESTADO=ID_CIUDAD_ESTADO-917 WHERE ID_CIUDAD_ESTADO>999;

COMMIT;


INSERT INTO ODS_HC_DIRECCIONES (DE_DIRECCION, DE_CP, ID_CIUDAD_ESTADO, FC_INSERT, FC_MODIFICACION)
SELECT PRODUCT_ADDRESS, PRODUCT_POSTAL_CODE, CIU.ID_CIUDAD_ESTADO, NOW(), NOW()
FROM TMP_DIR_SERVICIO2 DIR
INNER JOIN ODS.ODS_DM_PAISES PAI ON DIR.PRODUCT_COUNTRY=PAI.DE_PAIS
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADO CIU ON CONCAT(DIR.PRODUCT_CITY, PRODUCT_STATE)=CONCAT(CIU.DE_CIUDAD, CIU.DE_ESTADO);

COMMIT;

UPDATE ODS_HC_DIRECCIONES SET ID_DIRECCION=ID_DIRECCION-982502 WHERE ID_DIRECCION>999999;

COMMIT;

DROP TABLE IF EXISTS TMP_DIRECCIONES_CLIENTES;
DROP TABLE IF EXISTS TMP_DIR_SERVICIO;
DROP TABLE IF EXISTS TMP_DIR_SERVICIO2;
