USE ODS;

INSERT INTO ODS.ODS_DM_METODOS_PAGO VALUES (1, 'DIRECT DEBIT', NOW(), NOW());
INSERT INTO ODS.ODS_DM_METODOS_PAGO VALUES (2, 'CREDIT CARD', NOW(), NOW());
INSERT INTO ODS.ODS_DM_METODOS_PAGO VALUES (3, 'CHECK PAYMENT', NOW(), NOW());
INSERT INTO ODS.ODS_DM_METODOS_PAGO VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS.ODS_DM_METODOS_PAGO VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

INSERT INTO ODS.ODS_DM_CICLOS_FACTURACION VALUES (1, 'M01', NOW(), NOW());
INSERT INTO ODS.ODS_DM_CICLOS_FACTURACION VALUES (2, 'M15', NOW(), NOW());
INSERT INTO ODS.ODS_DM_CICLOS_FACTURACION VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS.ODS_DM_CICLOS_FACTURACION VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;


INSERT INTO ODS.ODS_HC_FACTURAS
SELECT CAST(FAC.BILL_REF_NO AS UNSIGNED) ID_FACTURA
, CASE WHEN CLI.ID_CLIENTE IS NULL THEN CAST(LPAD(FAC.CUSTOMER_ID,9,9) AS SIGNED INTEGER) ELSE CLI.ID_CLIENTE END ID_CLIENTE
, CASE WHEN TRIM(FAC.START_DATE)<>'' THEN STR_TO_DATE(TRIM(FAC.START_DATE),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('9999-12-31','%Y-%m-%d %H:%i:%s') END FC_INICIO
, CASE WHEN TRIM(FAC.END_DATE)<>'' THEN STR_TO_DATE(TRIM(FAC.END_DATE),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('9999-12-31','%Y-%m-%d %H:%i:%s') END FC_FIN
, CASE WHEN TRIM(FAC.STATEMENT_DATE)<>'' THEN STR_TO_DATE(TRIM(FAC.STATEMENT_DATE),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('9999-12-31','%Y-%m-%d %H:%i:%s') END FC_ESTADO
, CASE WHEN TRIM(FAC.PAYMENT_DATE)<>'' THEN STR_TO_DATE(TRIM(FAC.PAYMENT_DATE),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('9999-12-31','%Y-%m-%d %H:%i:%s') END FC_PAGO
, CI.ID_CICLO_FACTURACION
, ME.ID_METODO_PAGO
, CASE WHEN TRIM(FAC.AMOUNT)<>'' THEN CAST(AMOUNT AS DECIMAL(9,2)) ELSE '9999999.99' END CANTIDAD
, NOW() FC_INSERT
, STR_TO_DATE('9998-12-31 00:00:00','%Y-%m-%d %H:%i:%s') FC_MODIFICA
FROM STAGE.STG_FACTURAS_FCT FAC
LEFT OUTER JOIN ODS.ODS_HC_CLIENTES CLI ON CASE WHEN TRIM(CUSTOMER_ID)<>'' THEN TRIM(FAC.CUSTOMER_ID) ELSE 'DESCONOCIDO' END = CLI.ID_CLIENTE
INNER JOIN ODS.ODS_DM_CICLOS_FACTURACION CI ON CASE WHEN TRIM(FAC.BILL_CYCLE)<>'' THEN UPPER(TRIM(BILL_CYCLE)) ELSE 'DESCONOCIDO' END = CI.DE_CICLO_FACTURACION
INNER JOIN ODS.ODS_DM_METODOS_PAGO ME ON CASE WHEN TRIM(FAC.BILL_METHOD)<>'' THEN UPPER(TRIM(BILL_METHOD)) ELSE 'DESCONOCIDO' END = ME.DE_METODO_PAGO;

COMMIT;

