USE ODS;
/*
INSERT INTO ODS.ODS_DM_FASES (DE_FASE, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PHASE)), NOW(), NOW()
FROM STAGE.STG_ORDERS_CRM
WHERE TRIM(PHASE)<>'';

COMMIT;

INSERT INTO ODS.ODS_DM_FASES VALUES (98, 'NO APLICA', NOW(), NOW());
INSERT INTO ODS.ODS_DM_FASES VALUES (99, 'DESCONOCIDO', NOW(), NOW());

COMMIT;

INSERT INTO ODS.ODS_DM_AGENTES_PROV (DE_AGENTE_PROV, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(AGENT)),
NOW(), NOW()
FROM STAGE.STG_ORDERS_CRM
WHERE TRIM(AGENT)<>'';

COMMIT;

INSERT INTO ODS.ODS_DM_AGENTES_PROV VALUES (998, 'NO APLICA', NOW(), NOW());
INSERT INTO ODS.ODS_DM_AGENTES_PROV VALUES (999, 'DESCONOCIDO', NOW(), NOW());

COMMIT;
*/
INSERT INTO ODS.ODS_HC_PROVISIONES (ID, ID_SERVICIO, ID_FASE, ID_AGENTE_PROV, FC_INICIO, FC_FIN, FC_INSERT, FC_MODIFICACION)
SELECT CAST(ID AS SIGNED INTEGER) ID
, CAST(`ORDER` AS SIGNED INTEGER) ID_SERVICIO
, ID_FASE
, ID_AGENTE_PROV
, CASE WHEN TRIM(ORD.START_DT)<>'' THEN STR_TO_DATE(TRIM(ORD.START_DT),'%Y-%m-%d %H:%i:%s.%f') ELSE STR_TO_DATE('9999-12-31','%Y-%m-%d %H:%i:%s.%f') END FC_INICIO
, CASE WHEN TRIM(ORD.END_DT)<>'' THEN STR_TO_DATE(TRIM(ORD.END_DT),'%Y-%m-%d %H:%i:%s.%f') ELSE STR_TO_DATE('9999-12-31','%Y-%m-%d %H:%i:%s.%f') END FC_FIN
, NOW() FC_INSERT
, STR_TO_DATE('9998-12-31 00:00:00','%Y-%m-%d %H:%i:%s') FC_MODIFICA
FROM STAGE.STG_ORDERS_CRM ORD
INNER JOIN ODS.ODS_DM_FASES FA ON CASE WHEN TRIM(ORD.PHASE)<>'' THEN UPPER(TRIM(ORD.PHASE)) ELSE 'DESCONOCIDO' END = FA.DE_FASE
INNER JOIN ODS.ODS_DM_AGENTES_PROV AGE ON CASE WHEN TRIM(ORD.AGENT)<>'' THEN UPPER(TRIM(ORD.AGENT)) ELSE 'DESCONOCIDO' END = AGE.DE_AGENTE_PROV;

COMMIT;

