SELECT CASE WHEN DE_DIRECCION = 'DESCONOCIDO' THEN 9999 ELSE CASE WHEN DE_DIRECCION = 'NO APLICA' THEN 9998 ELSE SUBSTRING_INDEX(DE_DIRECCION,' ',1) END END NUM_VIA
, CASE WHEN DE_DIRECCION = 'DESCONOCIDO' THEN 'DESCONOCIDO' ELSE CASE WHEN DE_DIRECCION = 'NO APLICA' THEN 'NO APLICA' ELSE SUBSTR(DE_DIRECCION,LOCATE(' ',DE_DIRECCION,1)) END END NOMBRE_VIA
FROM ODS_HC_DIRECCIONES;